DROP TABLE IF EXISTS TBL_USER;

CREATE MEMORY TABLE TBL_USER
(
  ID INT IDENTITY PRIMARY KEY,
  USERNAME VARCHAR2(255) NOT NULL,
  PASSWORD VARCHAR2(255),
  FIRSTNAME NVARCHAR(100) NOT NULL,
  LASTNAME NVARCHAR(100) NOT NULL,
  GENDER CHAR(1),
  PHONE VARCHAR(100),
  EMAIL VARCHAR(100)
);

ALTER TABLE TBL_USER ADD CONSTRAINT USERNAME_UNIQUE UNIQUE(USERNAME);

INSERT INTO TBL_USER
(username, firstname, lastname, gender)
VALUES('tester', 'first', 'test', 'm');
-- DROP TABLE TBL_USER;